const siteInfoActionTypes =  {    
    RETRIEVED_SITEINFO_PORTAL_SETTINGS: "RETRIEVED_SITEINFO_PORTAL_SETTINGS",
    UPDATED_SITEINFO_PORTAL_SETTINGS: "UPDATED_SITEINFO_PORTAL_SETTINGS"
};
export default siteInfoActionTypes;
