const siteInfoActionTypes =  {    
    RETRIEVED_SITEINFO_PORTAL_SETTINGS: "RETRIEVED_SITEINFO_PORTAL_SETTINGS",
    UPDATED_SITEINFO_PORTAL_SETTINGS: "UPDATED_SITEINFO_PORTAL_SETTINGS",
    SITEINFO_PORTAL_SETTINS_CLIENT_MODIFIED: "SITEINFO_PORTAL_SETTINS_CLIENT_MODIFIED"
};
export default siteInfoActionTypes;
