<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootDirectory>$(MSBuildProjectDirectory)\..\..</RootDirectory>
    <OutputPath>bin</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <TargetFramework>net48</TargetFramework>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Settings.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Web" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DotNetNuke.Internal.SourceGenerators\DotNetNuke.Internal.SourceGenerators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <ProjectReference Include="..\DotNetNuke.Abstractions\DotNetNuke.Abstractions.csproj" />
    <ProjectReference Include="..\DotNetNuke.Log4Net\DotNetNuke.Log4Net.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\stylecop.json" Link="stylecop.json" />
    <Compile Include="..\..\SolutionInfo.cs" Link="SolutionInfo.cs" />
  </ItemGroup>

  <Import Project="..\..\DNN_Platform.build" />
  <Target Name="CopyBin" BeforeTargets="Build">
    <Copy SourceFiles="bin\DotNetNuke.Log4Net.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\DotNetNuke.Instrumentation.dll" DestinationFolder="$(WebsitePath)\bin" />
    <Copy SourceFiles="bin\DotNetNuke.Instrumentation.pdb" DestinationFolder="$(WebsitePath)\bin" />
    <Copy SourceFiles="bin\DotNetNuke.Instrumentation.xml" DestinationFolder="$(WebsitePath)\bin" />
    <Copy SourceFiles="bin\Microsoft.Extensions.Configuration.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Microsoft.Extensions.Configuration.Abstractions.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Microsoft.Extensions.Configuration.Binder.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Microsoft.Extensions.Configuration.FileExtensions.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Microsoft.Extensions.Configuration.Json.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Microsoft.Extensions.DependencyModel.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Microsoft.Extensions.FileProviders.Abstractions.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Microsoft.Extensions.FileProviders.Physical.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Microsoft.Extensions.Logging.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Microsoft.Extensions.Logging.Abstractions.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Microsoft.Extensions.Options.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Microsoft.Extensions.Primitives.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Serilog.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Serilog.Extensions.Logging.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Serilog.Settings.Configuration.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\Serilog.Sinks.File.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\System.Buffers.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\System.Diagnostics.DiagnosticSource.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\System.Memory.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\System.Numerics.Vectors.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\System.Text.Encodings.Web.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\System.Text.Json.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\System.Threading.Channels.dll" DestinationFolder="$(WebsitePath)\bin\" />
    <Copy SourceFiles="bin\System.ValueTuple.dll" DestinationFolder="$(WebsitePath)\bin\" />
  </Target>
</Project>