using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Dnn.PersonaBar.Pages.Services.Dto
{
    [DataContract]
    public class Url
    {
        [DataMember(Name = "id")]
        public int Id { get; set; }
        [DataMember(Name = "siteAlias")]
        public KeyValuePair<int, string> SiteAlias { get; set; }
        [DataMember(Name = "path")]
        public string Path { get; set; }
        public string PathWithNoExtension { get; set; }
        [DataMember(Name = "queryString")]
        public string QueryString { get; set; }
        [DataMember(Name = "locale")]
        public KeyValuePair<int, string> Locale { get; set; }
        [DataMember(Name = "statusCode")]
        public KeyValuePair<int, string> StatusCode { get; set; }
        [DataMember(Name = "siteAliasUsage")]
        public int SiteAliasUsage { get; set; }
        [DataMember(Name = "autoGenerated")]
        public bool IsSystem { get; set; }
        [DataMember(Name = "userName")]
        public string UserName { get; set; }
    }
}