const themeActionTypes = {
    RETRIEVED_CURRENT_THEMES: "RETRIEVED_CURRENT_THEMES",
    RETRIEVED_CURRENT_THEMEFILES: "RETRIEVED_CURRENT_THEMEFILES",

    RETRIEVED_EDITABLE_THEMEFILES: "RETRIEVED_EDITABLE_THEMEFILES",
    RETRIEVED_EDITABLE_TOKENS: "RETRIEVED_EDITABLE_TOKENS",
    RETRIEVED_EDITABLE_SETTINGS: "RETRIEVED_EDITABLE_SETTINGS",
    RETRIEVED_EDITABLE_VALUES: "RETRIEVED_EDITABLE_VALUES",

    RETRIEVED_THEMES: "RETRIEVED_THEMES",
    APPLY_THEME: "APPLY_THEME"
};
export default themeActionTypes;
