const themeActionTypes = {
    RETRIEVED_CURRENT_THEMES: "RETRIEVED_CURRENT_THEMES",
    RETRIEVED_CURRENT_THEMEFILES: "RETRIEVED_CURRENT_THEMEFILES",
    RETRIEVED_EDIT_THEMEFILES: "RETRIEVED_EDIT_THEMEFILES",
    RETRIEVED_THEMES: "RETRIEVED_THEMES",
    APPLY_THEME: "APPLY_THEME"
};
export default themeActionTypes;
