module.exports = {
    "react": "window.dnn.nodeModules.React",
    "react/lib/ReactMount": "window.dnn.nodeModules.ReactMount",
    "react/lib/ReactComponentWithPureRenderMixin": "window.dnn.nodeModules.ReactComponentWithPureRenderMixin",
    "redux": "window.dnn.nodeModules.Redux",
    "react-redux": "window.dnn.nodeModules.ReactRedux",
    "react-dom": "window.dnn.nodeModules.ReactDOM",
    "react-tabs": "window.dnn.nodeModules.ReactTabs",
    "redux-devtools": "window.dnn.nodeModules.ReduxDevTools",
    "redux-devtools-dock-monitor": "window.dnn.nodeModules.ReduxDevToolsDockMonitor",
    "redux-devtools-log-monitor": "window.dnn.nodeModules.ReduxDevToolsLogMonitor",
    "redux-immutable-state-invariant": "window.dnn.nodeModules.ReduxImmutableStateInvariant",
    "redux-thunk": "window.dnn.nodeModules.ReduxThunk",
    "react-collapse": "window.dnn.nodeModules.ReactCollapse",
    "react-modal": "window.dnn.nodeModules.ReactModal",
    "react-custom-scrollbars": "window.dnn.nodeModules.ReactCustomScrollBars",
    "react-tooltip": "window.dnn.nodeModules.ReactTooltip",
    "react-widgets": "window.dnn.nodeModules.ReactWidgets",
    "throttle-debounce": "window.dnn.nodeModules.ThrottleDebounce",
    "moment": "window.dnn.nodeModules.Moment",
    "es6-promise": "window.dnn.nodeModules.Es6Promise",
    "@dnnsoftware/dnn-react-common": "window.dnn.nodeModules.CommonComponents"
};
