const promptActionTypes = {
    RETRIEVED_COMMAND_LIST: "RETRIEVED_COMMAND_LIST",
    EXECUTED_COMMAND: "EXECUTED_COMMAND",
    EXECUTED_HELP_COMMAND: "EXECUTED_HELP_COMMAND",
    EXECUTED_LOCAL_COMMAND: "EXECUTED_LOCAL_COMMAND",
    CLEARED_HISTORY: "CLEARED_HISTORY",
    CLOSE_PROMPT: "CLOSE_PROMPT",
    EXIT_PROMPT: "EXIT_PROMPT",
    CLEARED_SCREEN: "CLEARED_SCREEN"
};
export default promptActionTypes;
