const userActionTypes = {
    RETRIEVED_USERS: "RETRIEVED_USERS",
    RETRIEVED_USER_DETAILS: "RETRIEVED_USER_DETAILS",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    RETRIEVED_USER_FILTERS: "RETRIEVED_USER_FILTERS"
};
export default userActionTypes;
