const userActionTypes = {
    RETRIEVED_USERS: "RETRIEVED_USERS",
    RETRIEVED_USER_DETAILS: "RETRIEVED_USER_DETAILS",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    ERASE_USER: "ERASE_USER",
    RETRIEVED_USER_FILTERS: "RETRIEVED_USER_FILTERS",
    USER_MADE_SUPERUSER: "USER_MADE_SUPERUSER"
};
export default userActionTypes;
