const importExportActionTypes =  { 
    RETRIEVED_PORTALS: "RETRIEVED_PORTALS",   
    RETRIEVED_JOBS: "RETRIEVED_JOBS",
    RETRIEVED_JOB_DETAILS: "RETRIEVED_JOB_DETAILS",
    RETRIEVED_PORTAL_LOGO: "RETRIEVED_PORTAL_LOGO"
};
export default importExportActionTypes;