/* eslint-disable spellcheck/spell-checker */
let timeZones =  [
    { value:"Dateline Standard Time", label: "(UTC-12:00) International Date Line West" },
    { value:"UTC-11", label: "(UTC-11:00) Coordinated Universal Time-11" },
	{ value:"Hawaiian Standard Time", label: "(UTC-10:00) Hawaii" },
    { value:"Alaskan Standard Time", label: "(UTC-09:00) Alaska" },
	{ value:"Pacific Standard Time (Mexico)", label: "(UTC-08:00) Baja California" },
	{ value:"Pacific Standard Time", label: "(UTC-08:00) Pacific Time (US & Canada)" },
	{ value:"US Mountain Standard Time", label: "(UTC-07:00) Arizona" },
	{ value:"Mountain Standard Time (Mexico)", label: "(UTC-07:00) Chihuahua, La Paz, Mazatlan" },
	{ value:"Mountain Standard Time", label: "(UTC-07:00) Mountain Time (US & Canada)" },
	{ value:"Central America Standard Time", label: "(UTC-06:00) Central America" },
	{ value:"Central Standard Time", label: "(UTC-06:00) Central Time (US & Canada)" },
	{ value:"Central Standard Time (Mexico)", label: "(UTC-06:00) Guadalajara, Mexico City, Monterrey" },
	{ value:"Canada Central Standard Time", label: "(UTC-06:00) Saskatchewan" },
	{ value:"SA Pacific Standard Time", label: "(UTC-05:00) Bogota, Lima, Quito, Rio Branco" },
	{ value:"Eastern Standard Time (Mexico)", label: "(UTC-05:00) Chetumal" },
	{ value:"Eastern Standard Time", label: "(UTC-05:00) Eastern Time (US & Canada)" },
	{ value:"US Eastern Standard Time", label: "(UTC-05:00) Indiana (East)" },
	{ value:"Venezuela Standard Time", label: "(UTC-04:30) Caracas" },
	{ value:"Paraguay Standard Time", label: "(UTC-04:00) Asuncion" },
	{ value:"Atlantic Standard Time", label: "(UTC-04:00) Atlantic Time (Canada)" },
	{ value:"Central Brazilian Standard Time", label: "(UTC-04:00) Cuiaba" },
	{ value:"SA Western Standard Time", label: "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan" },
	{ value:"Newfoundland Standard Time", label: "(UTC-03:30) Newfoundland" },
	{ value:"E. South America Standard Time", label: "(UTC-03:00) Brasilia" },
	{ value:"SA Eastern Standard Time", label: "(UTC-03:00) Cayenne, Fortaleza" },
	{ value:"Argentina Standard Time", label: "(UTC-03:00) City of Buenos Aires" },
	{ value:"Greenland Standard Time", label: "(UTC-03:00) Greenland" },
	{ value:"Montevideo Standard Time", label: "(UTC-03:00) Montevideo" },
	{ value:"Bahia Standard Time", label: "(UTC-03:00) Salvador" },
	{ value:"Pacific SA Standard Time", label: "(UTC-03:00) Santiago" },
	{ value:"UTC-02", label: "(UTC-02:00) Coordinated Universal Time-02" },
	{ value:"Mid-Atlantic Standard Time", label: "(UTC-02:00) Mid-Atlantic - Old" },
	{ value:"Azores Standard Time", label: "(UTC-01:00) Azores" },
	{ value:"Cape Verde Standard Time", label: "(UTC-01:00) Cabo Verde Is." },
	{ value:"Morocco Standard Time", label: "(UTC) Casablanca" },
	{ value:"UTC", label: "(UTC) Coordinated Universal Time" },
	{ value:"GMT Standard Time", label: "(UTC) Dublin, Edinburgh, Lisbon, London" },
	{ value:"Greenwich Standard Time", label: "(UTC) Monrovia, Reykjavik" },
	{ value:"W. Europe Standard Time", label: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" },
	{ value:"Central Europe Standard Time", label: "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague" },
	{ value:"Romance Standard Time", label: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris" },
	{ value:"Central European Standard Time", label: "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb" },
	{ value:"W. Central Africa Standard Time", label: "(UTC+01:00) West Central Africa" },
	{ value:"Namibia Standard Time", label: "(UTC+01:00) Windhoek" },
	{ value:"Jordan Standard Time", label: "(UTC+02:00) Amman" },
	{ value:"GTB Standard Time", label: "(UTC+02:00) Athens, Bucharest" },
	{ value:"Middle East Standard Time", label: "(UTC+02:00) Beirut" },
	{ value:"Egypt Standard Time", label: "(UTC+02:00) Cairo" },
	{ value:"Syria Standard Time", label: "(UTC+02:00) Damascus" },
	{ value:"E. Europe Standard Time", label: "(UTC+02:00) E. Europe" },
	{ value:"South Africa Standard Time", label: "(UTC+02:00) Harare, Pretoria" },
	{ value:"FLE Standard Time", label: "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius" },
	{ value:"Turkey Standard Time", label: "(UTC+02:00) Istanbul" },
	{ value:"Israel Standard Time", label: "(UTC+02:00) Jerusalem" },
	{ value:"Kaliningrad Standard Time", label: "(UTC+02:00) Kaliningrad (RTZ 1)" },
	{ value:"Libya Standard Time", label: "(UTC+02:00) Tripoli" },
	{ value:"Arabic Standard Time", label: "(UTC+03:00) Baghdad" },
	{ value:"Arab Standard Time", label: "(UTC+03:00) Kuwait, Riyadh" },
	{ value:"Belarus Standard Time", label: "(UTC+03:00) Minsk" },
	{ value:"Russian Standard Time", label: "(UTC+03:00) Moscow, St. Petersburg, Volgograd (RTZ 2)" },
	{ value:"E. Africa Standard Time", label: "(UTC+03:00) Nairobi" },
	{ value:"Iran Standard Time", label: "(UTC+03:30) Tehran" },
	{ value:"Arabian Standard Time", label: "(UTC+04:00) Abu Dhabi, Muscat" },
	{ value:"Azerbaijan Standard Time", label: "(UTC+04:00) Baku" },
	{ value:"Russia Time Zone 3", label: "(UTC+04:00) Izhevsk, Samara (RTZ 3)" },
	{ value:"Mauritius Standard Time", label: "(UTC+04:00) Port Louis" },
	{ value:"Georgian Standard Time", label: "(UTC+04:00) Tbilisi" },
	{ value:"Caucasus Standard Time", label: "(UTC+04:00) Yerevan" },
	{ value:"Afghanistan Standard Time", label: "(UTC+04:30) Kabul" },
	{ value:"West Asia Standard Time", label: "(UTC+05:00) Ashgabat, Tashkent" },
	{ value:"Ekaterinburg Standard Time", label: "(UTC+05:00) Ekaterinburg (RTZ 4)" },
	{ value:"Pakistan Standard Time", label: "(UTC+05:00) Islamabad, Karachi" },
	{ value:"India Standard Time", label: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi" },
	{ value:"Sri Lanka Standard Time", label: "(UTC+05:30) Sri Jayawardenepura" },
	{ value:"Nepal Standard Time", label: "(UTC+05:45) Kathmandu" },
	{ value:"Central Asia Standard Time", label: "(UTC+06:00) Astana" },
	{ value:"Bangladesh Standard Time", label: "(UTC+06:00) Dhaka" },
	{ value:"N. Central Asia Standard Time", label: "(UTC+06:00) Novosibirsk (RTZ 5)" },
	{ value:"Myanmar Standard Time", label: "(UTC+06:30) Yangon (Rangoon)" },
	{ value:"SE Asia Standard Time", label: "(UTC+07:00) Bangkok, Hanoi, Jakarta" },
	{ value:"North Asia Standard Time", label: "(UTC+07:00) Krasnoyarsk (RTZ 6)" },
	{ value:"China Standard Time", label: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi" },
	{ value:"North Asia East Standard Time", label: "(UTC+08:00) Irkutsk (RTZ 7)" },
	{ value:"Singapore Standard Time", label: "(UTC+08:00) Kuala Lumpur, Singapore" },
	{ value:"W. Australia Standard Time", label: "(UTC+08:00) Perth" },
	{ value:"Taipei Standard Time", label: "(UTC+08:00) Taipei" },
	{ value:"Ulaanbaatar Standard Time", label: "(UTC+08:00) Ulaanbaatar" },
	{ value:"North Korea Standard Time", label: "(UTC+08:30) Pyongyang" },
	{ value:"Tokyo Standard Time", label: "(UTC+09:00) Osaka, Sapporo, Tokyo" },
	{ value:"Korea Standard Time", label: "(UTC+09:00) Seoul" },
	{ value:"Yakutsk Standard Time", label: "(UTC+09:00) Yakutsk (RTZ 8)" },
	{ value:"Cen. Australia Standard Time", label: "(UTC+09:30) Adelaide" },
	{ value:"AUS Central Standard Time", label: "(UTC+09:30) Darwin" },
	{ value:"E. Australia Standard Time", label: "(UTC+10:00) Brisbane" },
	{ value:"AUS Eastern Standard Time", label: "(UTC+10:00) Canberra, Melbourne, Sydney" },
	{ value:"West Pacific Standard Time", label: "(UTC+10:00) Guam, Port Moresby" },
	{ value:"Tasmania Standard Time", label: "(UTC+10:00) Hobart" },
	{ value:"Magadan Standard Time", label: "(UTC+10:00) Magadan" },
	{ value:"Vladivostok Standard Time", label: "(UTC+10:00) Vladivostok, Magadan (RTZ 9)" },
	{ value:"Russia Time Zone 10", label: "(UTC+11:00) Chokurdakh (RTZ 10)" },
	{ value:"Central Pacific Standard Time", label: "(UTC+11:00) Solomon Is., New Caledonia" },
	{ value:"Russia Time Zone 11", label: "(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky (RTZ 11)" },
	{ value:"New Zealand Standard Time", label: "(UTC+12:00) Auckland, Wellington" },
	{ value:"UTC+12", label: "(UTC+12:00) Coordinated Universal Time+12" },
	{ value:"Fiji Standard Time", label: "(UTC+12:00) Fiji" },
	{ value:"Kamchatka Standard Time", label: "(UTC+12:00) Petropavlovsk-Kamchatsky - Old" },
	{ value:"Tonga Standard Time", label: "(UTC+13:00) Nuku'alofa" },
	{ value:"Samoa Standard Time", label: "(UTC+13:00) Samoa" },
	{ value:"Line Islands Standard Time", label: "(UTC+14:00) Kiritimati Island" }
];

export default timeZones;