const createPackageActionTypes = {
    RETRIEVED_PACKAGE_MANIFEST: "RETRIEVED_PACKAGE_MANIFEST",
    CREATED_PACKAGE_MANIFEST: "CREATED_PACKAGE_MANIFEST",
    CREATED_PACKAGE: "CREATED_PACKAGE",
    GO_TO_STEP: "GO_TO_STEP"
};
export default createPackageActionTypes;