const extensionActionTypes =  {    
    RETRIEVED_INSTALLED_PACKAGES: "RETRIEVED_INSTALLED_PACKAGES",
    RETRIEVED_AVAILABLE_PACKAGES: "RETRIEVED_AVAILABLE_PACKAGES",
    UPDATED_EXTENSION: "UPDATED_EXTENSION",
    DELETED_EXTENSION: "DELETED_EXTENSION",
    RETRIEVED_INSTALLED_PACKAGE_TYPES: "RETRIEVED_INSTALLED_PACKAGE_TYPES",
    RETRIEVED_AVAILABLE_PACKAGE_TYPES: "RETRIEVED_AVAILABLE_PACKAGE_TYPES",
    PARSED_INSTALLATION_PACKAGE: "PARSED_INSTALLATION_PACKAGE",
    GO_TO_WIZARD_STEP: "GO_TO_WIZARD_STEP",
    INSTALLED_EXTENSION_LOGS: "INSTALLED_EXTENSION_LOGS",
    CLEAR_PARSED_INSTALLATION_PACKAGE: "CLEAR_PARSED_INSTALLATION_PACKAGE"
};
export default extensionActionTypes;