const extensionActionTypes =  {    
    RETRIEVED_INSTALLED_PACKAGES: "RETRIEVED_INSTALLED_PACKAGES",
    RETRIEVED_AVAILABLE_PACKAGES: "RETRIEVED_AVAILABLE_PACKAGES",
    UPDATED_EXTENSION: "UPDATED_EXTENSION",
    DELETED_EXTENSION: "DELETED_EXTENSION",
    RETRIEVED_INSTALLED_PACKAGE_TYPES: "RETRIEVED_INSTALLED_PACKAGE_TYPES",
    RETRIEVED_AVAILABLE_PACKAGE_TYPES: "RETRIEVED_AVAILABLE_PACKAGE_TYPES",
    CREATED_NEW_MODULE: "CREATED_NEW_MODULE"
};
export default extensionActionTypes;