const folderActionTypes =  {    
    RETRIEVED_OWNER_FOLDERS: "RETRIEVED_OWNER_FOLDERS",
    RETRIEVED_MODULE_FOLDERS: "RETRIEVED_MODULE_FOLDERS",
    CREATED_NEW_OWNER_FOLDER: "CREATED_NEW_OWNER_FOLDER",
    CREATED_NEW_MODULE_FOLDER: "CREATED_NEW_MODULE_FOLDER",
    CREATED_NEW_MODULE: "CREATED_NEW_MODULE"
};
export default folderActionTypes;