const installationActionTypes =  {    
    PARSED_INSTALLATION_PACKAGE: "PARSED_INSTALLATION_PACKAGE",
    GO_TO_WIZARD_STEP: "GO_TO_WIZARD_STEP",
    INSTALLED_EXTENSION_LOGS: "INSTALLED_EXTENSION_LOGS",
    CLEAR_PARSED_INSTALLATION_PACKAGE: "CLEAR_PARSED_INSTALLATION_PACKAGE"
};
export default installationActionTypes;