const moduleDefinitionActionTypes = {
    UPDATED_MODULE_DEFINITION: "UPDATE_MODULE_DEFINITION",
    DELETED_MODULE_DEFINITION: "DELETE_MODULE_DEFINITION",
    SET_FORM_DIRT: "SET_FORM_DIRT",
    RETRIEVED_SOURCE_FOLDERS: "RETRIEVED_SOURCE_FOLDERS",
    RETRIEVED_SOURCE_FILES: "RETRIEVED_SOURCE_FILES",
    RETRIEVED_CONTROL_ICONS: "RETRIEVED_CONTROL_ICONS"
};
export default moduleDefinitionActionTypes;