const moduleDefinitionActionTypes =  {    
    EDIT_MODULE_DEFINITION: "EDIT_MODULE_DEFINITION",
    UPDATE_MODULE_DEFINITION: "UPDATE_MODULE_DEFINITION",
    DELETE_MODULE_DEFINITION: "DELETE_MODULE_DEFINITION",
    CLEAR_EDITED_MODULE_DEFINITION: "CLEAR_EDITED_MODULE_DEFINITION"
};
export default moduleDefinitionActionTypes;