const permissionActionTypes = {
    RETRIEVED_DESKTOPMODULE_PERMISSIONS: "RETRIEVED_DESKTOPMODULE_PERMISSIONS",
    UPDATED_DESKTOPMODULE_PERMISSIONS: "UPDATED_DESKTOPMODULE_PERMISSIONS"
};
export default permissionActionTypes;