name: Enhancement Request
description: Make an enhancement request
title: "[Enhancement]: "
labels: ["Status: New"]
assignees:
  - dnnsoftware/triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request!
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: description-of-problem
    attributes:
      label: Description of problem
      description: Is your enhancement request related to a problem? Provide a clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: description-of-solution
    attributes:
      label: Description of solution
      description: Provide a clear and concise description of the solution.
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Description of alternatives considered
      description: Provide a clear and concise description of any alternative solutions considered.
    validations:
      required: false
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: | 
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: contribution-interest
    attributes:
      label: Do you plan to contribute code for this enhancement?
      description: We would like to know if you are willing to take ownership of this enhancement.
      options:
        - label: "Yes"
          required: false
  - type: checkboxes
    id: sponsorship-interest
    attributes:
      label: Would you be interested in sponsoring this enhancement?
      description: There are many developers in this community that may be willing to work on this.
      options:
        - label: "Yes"
          required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
