//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebControls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebControls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebControls", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items checked.
        /// </summary>
        internal static string AllItemsCheckedString_Text {
            get {
                return ResourceManager.GetString("AllItemsCheckedString.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel_Text {
            get {
                return ResourceManager.GetString("Cancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all.
        /// </summary>
        internal static string CheckAllString_Text {
            get {
                return ResourceManager.GetString("CheckAllString.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items in the list..
        /// </summary>
        internal static string ComboBox_EmptyMessage {
            get {
                return ResourceManager.GetString("ComboBox.EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Matched.
        /// </summary>
        internal static string ConfirmPasswordMatched_Text {
            get {
                return ResourceManager.GetString("ConfirmPasswordMatched.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        internal static string ConfirmPasswordUnmatched_Text {
            get {
                return ResourceManager.GetString("ConfirmPasswordUnmatched.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least {0} characters.
        /// </summary>
        internal static string CriteriaAtLeastNChars_Text {
            get {
                return ResourceManager.GetString("CriteriaAtLeastNChars.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least {0} special characters (!,@,#,%).
        /// </summary>
        internal static string CriteriaAtLeastNSpecialChars_Text {
            get {
                return ResourceManager.GetString("CriteriaAtLeastNSpecialChars.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One lower-case letter.
        /// </summary>
        internal static string CriteriaOneLowerCaseLetter_Text {
            get {
                return ResourceManager.GetString("CriteriaOneLowerCaseLetter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One number.
        /// </summary>
        internal static string CriteriaOneNumber_Text {
            get {
                return ResourceManager.GetString("CriteriaOneNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One upper-case letter.
        /// </summary>
        internal static string CriteriaOneUpperCaseLetter_Text {
            get {
                return ResourceManager.GetString("CriteriaOneUpperCaseLetter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special character (!,@,#,%).
        /// </summary>
        internal static string CriteriaSpecialChar_Text {
            get {
                return ResourceManager.GetString("CriteriaSpecialChar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string FieldSuffix_Text {
            get {
                return ResourceManager.GetString("FieldSuffix.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string FileUpload_CloseButton_Text {
            get {
                return ResourceManager.GetString("FileUpload.CloseButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing File.
        /// </summary>
        internal static string FileUpload_DecompressingFile_Text {
            get {
                return ResourceManager.GetString("FileUpload.DecompressingFile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress Zip Files.
        /// </summary>
        internal static string FileUpload_DecompressLabel_Text {
            get {
                return ResourceManager.GetString("FileUpload.DecompressLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag files here or click to browse.
        /// </summary>
        internal static string FileUpload_DragAndDropAreaTitle_Text {
            get {
                return ResourceManager.GetString("FileUpload.DragAndDropAreaTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser does not support empty file uploads.
        /// </summary>
        internal static string FileUpload_EmptyFileUpload_Error {
            get {
                return ResourceManager.GetString("FileUpload.EmptyFileUpload.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string FileUpload_ErrorDialogTitle_Text {
            get {
                return ResourceManager.GetString("FileUpload.ErrorDialogTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you want to upload already exists in this folder.
        /// </summary>
        internal static string FileUpload_FileAlreadyExists_Error {
            get {
                return ResourceManager.GetString("FileUpload.FileAlreadyExists.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size bigger than {0}.
        /// </summary>
        internal static string FileUpload_FileIsTooLarge_Error {
            get {
                return ResourceManager.GetString("FileUpload.FileIsTooLarge.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload cancelled.
        /// </summary>
        internal static string FileUpload_FileUploadCancelled_Error {
            get {
                return ResourceManager.GetString("FileUpload.FileUploadCancelled.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded.
        /// </summary>
        internal static string FileUpload_FileUploaded_Text {
            get {
                return ResourceManager.GetString("FileUpload.FileUploaded.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed.
        /// </summary>
        internal static string FileUpload_FileUploadFailed_Error {
            get {
                return ResourceManager.GetString("FileUpload.FileUploadFailed.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some selected files with invalid extensions are excluded from upload.  You can only upload files with the following extensions: {0}..
        /// </summary>
        internal static string FileUpload_InvalidFileExtensions_Error {
            get {
                return ResourceManager.GetString("FileUpload.InvalidFileExtensions.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep.
        /// </summary>
        internal static string FileUpload_KeepButton_Text {
            get {
                return ResourceManager.GetString("FileUpload.KeepButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string FileUpload_ReplaceButton_Text {
            get {
                return ResourceManager.GetString("FileUpload.ReplaceButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        internal static string FileUpload_Title_Text {
            get {
                return ResourceManager.GetString("FileUpload.Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You connot upload more than {0} file(s) at once..
        /// </summary>
        internal static string FileUpload_TooManyFiles_Error {
            get {
                return ResourceManager.GetString("FileUpload.TooManyFiles.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        internal static string FileUpload_UploadFileMethod_Text {
            get {
                return ResourceManager.GetString("FileUpload.UploadFileMethod.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string FileUpload_UploadFromWebButton_Text {
            get {
                return ResourceManager.GetString("FileUpload.UploadFromWebButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From URL.
        /// </summary>
        internal static string FileUpload_UploadFromWebMethod_Text {
            get {
                return ResourceManager.GetString("FileUpload.UploadFromWebMethod.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload stopped.
        /// </summary>
        internal static string FileUpload_UploadStopped_Text {
            get {
                return ResourceManager.GetString("FileUpload.UploadStopped.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload To:.
        /// </summary>
        internal static string FileUpload_UploadToFolderLabel_Text {
            get {
                return ResourceManager.GetString("FileUpload.UploadToFolderLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Resource Url like http://SomeWebSite.com/Images/About.png.
        /// </summary>
        internal static string FileUpload_UrlTooltip_Text {
            get {
                return ResourceManager.GetString("FileUpload.UrlTooltip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File_Text {
            get {
                return ResourceManager.GetString("File.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder_Text {
            get {
                return ResourceManager.GetString("Folder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items checked.
        /// </summary>
        internal static string ItemsCheckedString_Text {
            get {
                return ResourceManager.GetString("ItemsCheckedString.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Folder.
        /// </summary>
        internal static string MyFolder_Text {
            get {
                return ResourceManager.GetString("MyFolder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches.
        /// </summary>
        internal static string NoMatches_Text {
            get {
                return ResourceManager.GetString("NoMatches.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to view any files on the file system.
        /// </summary>
        internal static string NoPermission_Text {
            get {
                return ResourceManager.GetString("NoPermission.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok_Text {
            get {
                return ResourceManager.GetString("Ok.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fair.
        /// </summary>
        internal static string PasswordStrengthFair_Text {
            get {
                return ResourceManager.GetString("PasswordStrengthFair.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -character minimum.
        /// </summary>
        internal static string PasswordStrengthMinLength_Text {
            get {
                return ResourceManager.GetString("PasswordStrengthMinLength.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strong.
        /// </summary>
        internal static string PasswordStrengthStrong_Text {
            get {
                return ResourceManager.GetString("PasswordStrengthStrong.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weak.
        /// </summary>
        internal static string PasswordStrengthWeak_Text {
            get {
                return ResourceManager.GetString("PasswordStrengthWeak.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Root.
        /// </summary>
        internal static string PortalRoot_Text {
            get {
                return ResourceManager.GetString("PortalRoot.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        internal static string Save_Text {
            get {
                return ResourceManager.GetString("Save.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items &lt;b&gt;1&lt;/b&gt;-&lt;b&gt;{0}&lt;/b&gt; out of &lt;b&gt;{1}&lt;/b&gt;.
        /// </summary>
        internal static string ShowMoreFormatString_Text {
            get {
                return ResourceManager.GetString("ShowMoreFormatString.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type {1} is not valid in this context. Valid File Types Include: {0}.
        /// </summary>
        internal static string UploadError_Text {
            get {
                return ResourceManager.GetString("UploadError.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        internal static string Upload_Text {
            get {
                return ResourceManager.GetString("Upload.Text", resourceCulture);
            }
        }
    }
}
