const pageActionTypes =  {
    LOAD_PAGE: "LOAD_PAGE",
    LOADED_PAGE: "LOADED_PAGE",
    ERROR_LOADING_PAGE: "ERROR_LOADING_PAGE",
    SAVE_PAGE: "SAVE_PAGE",
    SAVED_PAGE: "SAVED_PAGE",
    ERROR_SAVING_PAGE: "ERROR_SAVING_PAGE",
    CHANGE_FIELD_VALUE: "CHANGE_FIELD_VALUE"
};

export default pageActionTypes;
