const pageActionTypes =  {
    LOAD_PAGE: "LOAD_PAGE",
    LOADED_PAGE: "LOADED_PAGE",
    ERROR_LOADING_PAGE: "ERROR_LOADING_PAGE",
    SAVE_PAGE: "SAVE_PAGE",
    SAVED_PAGE: "SAVED_PAGE",
    ERROR_SAVING_PAGE: "ERROR_SAVING_PAGE",
    CHANGE_FIELD_VALUE: "CHANGE_FIELD_VALUE",
    CHANGE_PERMISSIONS: "CHANGE_PERMISSIONS",
    FETCH_CACHE_PROVIDER_LIST: "FETCH_CACHE_PROVIDER_LIST",
    FETCHED_CACHE_PROVIDER_LIST: "FETCHED_CACHE_PROVIDER_LIST",
    ERROR_FETCHING_CACHE_PROVIDER_LIST: "ERROR_FETCHING_CACHE_PROVIDER_LIST"
};

export default pageActionTypes;
