const pageActionTypes =  {
    CANCEL_PAGE: "CANCEL_PAGE",
    LOAD_PAGE: "LOAD_PAGE",
    LOADED_PAGE: "LOADED_PAGE",
    ERROR_LOADING_PAGE: "ERROR_LOADING_PAGE",
    SAVE_PAGE: "SAVE_PAGE",
    SAVED_PAGE: "SAVED_PAGE",
    ERROR_SAVING_PAGE: "ERROR_SAVING_PAGE",
    CHANGE_FIELD_VALUE: "CHANGE_FIELD_VALUE",
    CHANGE_PERMISSIONS: "CHANGE_PERMISSIONS",
    FETCH_CACHE_PROVIDER_LIST: "FETCH_CACHE_PROVIDER_LIST",
    FETCHED_CACHE_PROVIDER_LIST: "FETCHED_CACHE_PROVIDER_LIST",
    ERROR_FETCHING_CACHE_PROVIDER_LIST: "ERROR_FETCHING_CACHE_PROVIDER_LIST",
    TOGGLE_EDIT_PAGE_MODULE: "TOGGLE_EDIT_PAGE_MODULE",
    DELETING_PAGE_MODULE: "DELETING_PAGE_MODULE",
    DELETED_PAGE_MODULE: "DELETED_PAGE_MODULE",
    ERROR_DELETING_PAGE_MODULE: "ERROR_DELETING_PAGE_MODULE",
    COPYING_APPEARANCE_TO_DESCENDANT_PAGES: "COPYING_APPEARANCE_TO_DESCENDANT_PAGES",
    COPIED_APPEARANCE_TO_DESCENDANT_PAGES: "COPIED_APPEARANCE_TO_DESCENDANT_PAGES",
    ERROR_COPYING_APPEARANCE_TO_DESCENDANT_PAGES: "ERROR_COPYING_APPEARANCE_TO_DESCENDANT_PAGES",
    ADD_CUSTOM_URL: "ADD_CUSTOM_URL"
};

export default pageActionTypes;
