/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GetFolderContentResponse, Item } from "./services/ItemsClient";
import { FolderTreeItem } from "./services/InternalServicesClient";
export { GetFolderContentResponse, Item } from "./services/ItemsClient";
export { FolderTreeItem } from "./services/InternalServicesClient";
export namespace Components {
    interface DnnActionCopyUrl {
        /**
          * The list of items to copy.
         */
        "items": Item[];
    }
    interface DnnActionCreateFolder {
        /**
          * The ID of the parent folder
         */
        "parentFolderId": number;
    }
    interface DnnActionDeleteItems {
        /**
          * The list of items to delete.
         */
        "items": Item[];
    }
    interface DnnActionDownloadItem {
        /**
          * The item to download.
         */
        "item": Item;
    }
    interface DnnActionEditItem {
        /**
          * The item to edit.
         */
        "item": Item;
    }
    interface DnnActionMoveItems {
        /**
          * The list of items to move.
         */
        "items": Item[];
    }
    interface DnnActionOpenFile {
        /**
          * The item to open.
         */
        "item": Item;
    }
    interface DnnActionUnlinkItems {
        /**
          * The list of items selected.
         */
        "items": Item[];
    }
    interface DnnActionUploadFile {
        /**
          * The ID of the parent folder.
         */
        "parentFolderId": number;
    }
    interface DnnResourceManager {
        /**
          * The ID of the module.
         */
        "moduleId": number;
    }
    interface DnnRmActionsBar {
    }
    interface DnnRmCreateFolder {
    }
    interface DnnRmDeleteItems {
        /**
          * The list of items to delete.
         */
        "items": Item[];
    }
    interface DnnRmEditFile {
        /**
          * The ID of the folder to edit.
         */
        "fileId": number;
    }
    interface DnnRmEditFolder {
        /**
          * The ID of the folder to edit.
         */
        "folderId": number;
    }
    interface DnnRmFileContextMenu {
        /**
          * The item that triggered this menu.
         */
        "item": Item;
    }
    interface DnnRmFilesPane {
        /**
          * Defines how much more pixels to load under the fold.
          * @default 5000
         */
        "preloadOffset": number;
    }
    interface DnnRmFolderContextMenu {
        /**
          * The item that triggered this menu.
         */
        "item": Item;
    }
    interface DnnRmFolderList {
    }
    interface DnnRmFolderListItem {
        /**
          * If true, this node will be expanded on load.
          * @default false
         */
        "expanded": boolean;
        /**
          * The basic information about the folder
         */
        "folder": FolderTreeItem;
        /**
          * The ID of the parent folder.
         */
        "parentFolderId": number;
        /**
          * Indicates if this item is the currently selected one.
         */
        "selectedFolder": FolderTreeItem;
    }
    interface DnnRmFolderMappings {
    }
    interface DnnRmItemsCardview {
        /**
          * The list of current items.
         */
        "currentItems": GetFolderContentResponse;
    }
    interface DnnRmItemsListview {
        /**
          * The list of current items.
         */
        "currentItems": GetFolderContentResponse;
    }
    interface DnnRmLeftPane {
    }
    interface DnnRmMoveItems {
        /**
          * The list of items to delete.
         */
        "items": Item[];
    }
    interface DnnRmProgressBar {
        /**
          * Defines the max progress value.
          * @default 100
         */
        "max": number;
        /**
          * Defines the current progress value.
          * @default 0
         */
        "value": number;
    }
    interface DnnRmQueuedFile {
        /**
          * Whether to extract uploaded zip files.
          * @default false
         */
        "extract": boolean;
        /**
          * The file to upload.
         */
        "file": File;
        /**
          * Optionally limit the file types that can be uploaded.
         */
        "filter": string;
        /**
          * The maximal allowed file upload size
         */
        "maxUploadFileSize": number;
        /**
          * The validation code to use for uploads.
         */
        "validationCode": string;
    }
    interface DnnRmRightPane {
    }
    interface DnnRmStatusBar {
    }
    interface DnnRmTopBar {
    }
    interface DnnRmUnlinkItems {
        /**
          * The list of items to delete.
         */
        "items": Item[];
    }
    interface DnnRmUploadFile {
    }
}
export interface DnnActionUploadFileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnActionUploadFileElement;
}
export interface DnnRmCreateFolderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnRmCreateFolderElement;
}
export interface DnnRmDeleteItemsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnRmDeleteItemsElement;
}
export interface DnnRmEditFileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnRmEditFileElement;
}
export interface DnnRmEditFolderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnRmEditFolderElement;
}
export interface DnnRmFolderListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnRmFolderListElement;
}
export interface DnnRmFolderListItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnRmFolderListItemElement;
}
export interface DnnRmItemsCardviewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnRmItemsCardviewElement;
}
export interface DnnRmItemsListviewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnRmItemsListviewElement;
}
export interface DnnRmMoveItemsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnRmMoveItemsElement;
}
export interface DnnRmUnlinkItemsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnRmUnlinkItemsElement;
}
export interface DnnRmUploadFileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDnnRmUploadFileElement;
}
declare global {
    interface HTMLDnnActionCopyUrlElement extends Components.DnnActionCopyUrl, HTMLStencilElement {
    }
    var HTMLDnnActionCopyUrlElement: {
        prototype: HTMLDnnActionCopyUrlElement;
        new (): HTMLDnnActionCopyUrlElement;
    };
    interface HTMLDnnActionCreateFolderElement extends Components.DnnActionCreateFolder, HTMLStencilElement {
    }
    var HTMLDnnActionCreateFolderElement: {
        prototype: HTMLDnnActionCreateFolderElement;
        new (): HTMLDnnActionCreateFolderElement;
    };
    interface HTMLDnnActionDeleteItemsElement extends Components.DnnActionDeleteItems, HTMLStencilElement {
    }
    var HTMLDnnActionDeleteItemsElement: {
        prototype: HTMLDnnActionDeleteItemsElement;
        new (): HTMLDnnActionDeleteItemsElement;
    };
    interface HTMLDnnActionDownloadItemElement extends Components.DnnActionDownloadItem, HTMLStencilElement {
    }
    var HTMLDnnActionDownloadItemElement: {
        prototype: HTMLDnnActionDownloadItemElement;
        new (): HTMLDnnActionDownloadItemElement;
    };
    interface HTMLDnnActionEditItemElement extends Components.DnnActionEditItem, HTMLStencilElement {
    }
    var HTMLDnnActionEditItemElement: {
        prototype: HTMLDnnActionEditItemElement;
        new (): HTMLDnnActionEditItemElement;
    };
    interface HTMLDnnActionMoveItemsElement extends Components.DnnActionMoveItems, HTMLStencilElement {
    }
    var HTMLDnnActionMoveItemsElement: {
        prototype: HTMLDnnActionMoveItemsElement;
        new (): HTMLDnnActionMoveItemsElement;
    };
    interface HTMLDnnActionOpenFileElement extends Components.DnnActionOpenFile, HTMLStencilElement {
    }
    var HTMLDnnActionOpenFileElement: {
        prototype: HTMLDnnActionOpenFileElement;
        new (): HTMLDnnActionOpenFileElement;
    };
    interface HTMLDnnActionUnlinkItemsElement extends Components.DnnActionUnlinkItems, HTMLStencilElement {
    }
    var HTMLDnnActionUnlinkItemsElement: {
        prototype: HTMLDnnActionUnlinkItemsElement;
        new (): HTMLDnnActionUnlinkItemsElement;
    };
    interface HTMLDnnActionUploadFileElementEventMap {
        "dnnRmFoldersChanged": void;
    }
    interface HTMLDnnActionUploadFileElement extends Components.DnnActionUploadFile, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnActionUploadFileElementEventMap>(type: K, listener: (this: HTMLDnnActionUploadFileElement, ev: DnnActionUploadFileCustomEvent<HTMLDnnActionUploadFileElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnActionUploadFileElementEventMap>(type: K, listener: (this: HTMLDnnActionUploadFileElement, ev: DnnActionUploadFileCustomEvent<HTMLDnnActionUploadFileElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnActionUploadFileElement: {
        prototype: HTMLDnnActionUploadFileElement;
        new (): HTMLDnnActionUploadFileElement;
    };
    interface HTMLDnnResourceManagerElement extends Components.DnnResourceManager, HTMLStencilElement {
    }
    var HTMLDnnResourceManagerElement: {
        prototype: HTMLDnnResourceManagerElement;
        new (): HTMLDnnResourceManagerElement;
    };
    interface HTMLDnnRmActionsBarElement extends Components.DnnRmActionsBar, HTMLStencilElement {
    }
    var HTMLDnnRmActionsBarElement: {
        prototype: HTMLDnnRmActionsBarElement;
        new (): HTMLDnnRmActionsBarElement;
    };
    interface HTMLDnnRmCreateFolderElementEventMap {
        "dnnRmFoldersChanged": void;
    }
    interface HTMLDnnRmCreateFolderElement extends Components.DnnRmCreateFolder, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnRmCreateFolderElementEventMap>(type: K, listener: (this: HTMLDnnRmCreateFolderElement, ev: DnnRmCreateFolderCustomEvent<HTMLDnnRmCreateFolderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnRmCreateFolderElementEventMap>(type: K, listener: (this: HTMLDnnRmCreateFolderElement, ev: DnnRmCreateFolderCustomEvent<HTMLDnnRmCreateFolderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnRmCreateFolderElement: {
        prototype: HTMLDnnRmCreateFolderElement;
        new (): HTMLDnnRmCreateFolderElement;
    };
    interface HTMLDnnRmDeleteItemsElementEventMap {
        "dnnRmFoldersChanged": void;
    }
    interface HTMLDnnRmDeleteItemsElement extends Components.DnnRmDeleteItems, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnRmDeleteItemsElementEventMap>(type: K, listener: (this: HTMLDnnRmDeleteItemsElement, ev: DnnRmDeleteItemsCustomEvent<HTMLDnnRmDeleteItemsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnRmDeleteItemsElementEventMap>(type: K, listener: (this: HTMLDnnRmDeleteItemsElement, ev: DnnRmDeleteItemsCustomEvent<HTMLDnnRmDeleteItemsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnRmDeleteItemsElement: {
        prototype: HTMLDnnRmDeleteItemsElement;
        new (): HTMLDnnRmDeleteItemsElement;
    };
    interface HTMLDnnRmEditFileElementEventMap {
        "dnnRmFoldersChanged": void;
    }
    interface HTMLDnnRmEditFileElement extends Components.DnnRmEditFile, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnRmEditFileElementEventMap>(type: K, listener: (this: HTMLDnnRmEditFileElement, ev: DnnRmEditFileCustomEvent<HTMLDnnRmEditFileElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnRmEditFileElementEventMap>(type: K, listener: (this: HTMLDnnRmEditFileElement, ev: DnnRmEditFileCustomEvent<HTMLDnnRmEditFileElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnRmEditFileElement: {
        prototype: HTMLDnnRmEditFileElement;
        new (): HTMLDnnRmEditFileElement;
    };
    interface HTMLDnnRmEditFolderElementEventMap {
        "dnnRmFoldersChanged": void;
    }
    interface HTMLDnnRmEditFolderElement extends Components.DnnRmEditFolder, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnRmEditFolderElementEventMap>(type: K, listener: (this: HTMLDnnRmEditFolderElement, ev: DnnRmEditFolderCustomEvent<HTMLDnnRmEditFolderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnRmEditFolderElementEventMap>(type: K, listener: (this: HTMLDnnRmEditFolderElement, ev: DnnRmEditFolderCustomEvent<HTMLDnnRmEditFolderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnRmEditFolderElement: {
        prototype: HTMLDnnRmEditFolderElement;
        new (): HTMLDnnRmEditFolderElement;
    };
    interface HTMLDnnRmFileContextMenuElement extends Components.DnnRmFileContextMenu, HTMLStencilElement {
    }
    var HTMLDnnRmFileContextMenuElement: {
        prototype: HTMLDnnRmFileContextMenuElement;
        new (): HTMLDnnRmFileContextMenuElement;
    };
    interface HTMLDnnRmFilesPaneElement extends Components.DnnRmFilesPane, HTMLStencilElement {
    }
    var HTMLDnnRmFilesPaneElement: {
        prototype: HTMLDnnRmFilesPaneElement;
        new (): HTMLDnnRmFilesPaneElement;
    };
    interface HTMLDnnRmFolderContextMenuElement extends Components.DnnRmFolderContextMenu, HTMLStencilElement {
    }
    var HTMLDnnRmFolderContextMenuElement: {
        prototype: HTMLDnnRmFolderContextMenuElement;
        new (): HTMLDnnRmFolderContextMenuElement;
    };
    interface HTMLDnnRmFolderListElementEventMap {
        "dnnRmFolderListFolderPicked": FolderTreeItem;
        "dnnRmcontextMenuOpened": number;
    }
    interface HTMLDnnRmFolderListElement extends Components.DnnRmFolderList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnRmFolderListElementEventMap>(type: K, listener: (this: HTMLDnnRmFolderListElement, ev: DnnRmFolderListCustomEvent<HTMLDnnRmFolderListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnRmFolderListElementEventMap>(type: K, listener: (this: HTMLDnnRmFolderListElement, ev: DnnRmFolderListCustomEvent<HTMLDnnRmFolderListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnRmFolderListElement: {
        prototype: HTMLDnnRmFolderListElement;
        new (): HTMLDnnRmFolderListElement;
    };
    interface HTMLDnnRmFolderListItemElementEventMap {
        "dnnRmFolderListItemClicked": FolderTreeItem;
    }
    interface HTMLDnnRmFolderListItemElement extends Components.DnnRmFolderListItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnRmFolderListItemElementEventMap>(type: K, listener: (this: HTMLDnnRmFolderListItemElement, ev: DnnRmFolderListItemCustomEvent<HTMLDnnRmFolderListItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnRmFolderListItemElementEventMap>(type: K, listener: (this: HTMLDnnRmFolderListItemElement, ev: DnnRmFolderListItemCustomEvent<HTMLDnnRmFolderListItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnRmFolderListItemElement: {
        prototype: HTMLDnnRmFolderListItemElement;
        new (): HTMLDnnRmFolderListItemElement;
    };
    interface HTMLDnnRmFolderMappingsElement extends Components.DnnRmFolderMappings, HTMLStencilElement {
    }
    var HTMLDnnRmFolderMappingsElement: {
        prototype: HTMLDnnRmFolderMappingsElement;
        new (): HTMLDnnRmFolderMappingsElement;
    };
    interface HTMLDnnRmItemsCardviewElementEventMap {
        "dnnRmFolderDoubleClicked": number;
        "dnnRmFileDoubleClicked": string;
    }
    interface HTMLDnnRmItemsCardviewElement extends Components.DnnRmItemsCardview, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnRmItemsCardviewElementEventMap>(type: K, listener: (this: HTMLDnnRmItemsCardviewElement, ev: DnnRmItemsCardviewCustomEvent<HTMLDnnRmItemsCardviewElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnRmItemsCardviewElementEventMap>(type: K, listener: (this: HTMLDnnRmItemsCardviewElement, ev: DnnRmItemsCardviewCustomEvent<HTMLDnnRmItemsCardviewElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnRmItemsCardviewElement: {
        prototype: HTMLDnnRmItemsCardviewElement;
        new (): HTMLDnnRmItemsCardviewElement;
    };
    interface HTMLDnnRmItemsListviewElementEventMap {
        "dnnRmFolderDoubleClicked": number;
        "dnnRmFileDoubleClicked": string;
    }
    interface HTMLDnnRmItemsListviewElement extends Components.DnnRmItemsListview, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnRmItemsListviewElementEventMap>(type: K, listener: (this: HTMLDnnRmItemsListviewElement, ev: DnnRmItemsListviewCustomEvent<HTMLDnnRmItemsListviewElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnRmItemsListviewElementEventMap>(type: K, listener: (this: HTMLDnnRmItemsListviewElement, ev: DnnRmItemsListviewCustomEvent<HTMLDnnRmItemsListviewElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnRmItemsListviewElement: {
        prototype: HTMLDnnRmItemsListviewElement;
        new (): HTMLDnnRmItemsListviewElement;
    };
    interface HTMLDnnRmLeftPaneElement extends Components.DnnRmLeftPane, HTMLStencilElement {
    }
    var HTMLDnnRmLeftPaneElement: {
        prototype: HTMLDnnRmLeftPaneElement;
        new (): HTMLDnnRmLeftPaneElement;
    };
    interface HTMLDnnRmMoveItemsElementEventMap {
        "dnnRmFoldersChanged": void;
    }
    interface HTMLDnnRmMoveItemsElement extends Components.DnnRmMoveItems, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnRmMoveItemsElementEventMap>(type: K, listener: (this: HTMLDnnRmMoveItemsElement, ev: DnnRmMoveItemsCustomEvent<HTMLDnnRmMoveItemsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnRmMoveItemsElementEventMap>(type: K, listener: (this: HTMLDnnRmMoveItemsElement, ev: DnnRmMoveItemsCustomEvent<HTMLDnnRmMoveItemsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnRmMoveItemsElement: {
        prototype: HTMLDnnRmMoveItemsElement;
        new (): HTMLDnnRmMoveItemsElement;
    };
    interface HTMLDnnRmProgressBarElement extends Components.DnnRmProgressBar, HTMLStencilElement {
    }
    var HTMLDnnRmProgressBarElement: {
        prototype: HTMLDnnRmProgressBarElement;
        new (): HTMLDnnRmProgressBarElement;
    };
    interface HTMLDnnRmQueuedFileElement extends Components.DnnRmQueuedFile, HTMLStencilElement {
    }
    var HTMLDnnRmQueuedFileElement: {
        prototype: HTMLDnnRmQueuedFileElement;
        new (): HTMLDnnRmQueuedFileElement;
    };
    interface HTMLDnnRmRightPaneElement extends Components.DnnRmRightPane, HTMLStencilElement {
    }
    var HTMLDnnRmRightPaneElement: {
        prototype: HTMLDnnRmRightPaneElement;
        new (): HTMLDnnRmRightPaneElement;
    };
    interface HTMLDnnRmStatusBarElement extends Components.DnnRmStatusBar, HTMLStencilElement {
    }
    var HTMLDnnRmStatusBarElement: {
        prototype: HTMLDnnRmStatusBarElement;
        new (): HTMLDnnRmStatusBarElement;
    };
    interface HTMLDnnRmTopBarElement extends Components.DnnRmTopBar, HTMLStencilElement {
    }
    var HTMLDnnRmTopBarElement: {
        prototype: HTMLDnnRmTopBarElement;
        new (): HTMLDnnRmTopBarElement;
    };
    interface HTMLDnnRmUnlinkItemsElementEventMap {
        "dnnRmFoldersChanged": void;
    }
    interface HTMLDnnRmUnlinkItemsElement extends Components.DnnRmUnlinkItems, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnRmUnlinkItemsElementEventMap>(type: K, listener: (this: HTMLDnnRmUnlinkItemsElement, ev: DnnRmUnlinkItemsCustomEvent<HTMLDnnRmUnlinkItemsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnRmUnlinkItemsElementEventMap>(type: K, listener: (this: HTMLDnnRmUnlinkItemsElement, ev: DnnRmUnlinkItemsCustomEvent<HTMLDnnRmUnlinkItemsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnRmUnlinkItemsElement: {
        prototype: HTMLDnnRmUnlinkItemsElement;
        new (): HTMLDnnRmUnlinkItemsElement;
    };
    interface HTMLDnnRmUploadFileElementEventMap {
        "dnnRmFoldersChanged": void;
    }
    interface HTMLDnnRmUploadFileElement extends Components.DnnRmUploadFile, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDnnRmUploadFileElementEventMap>(type: K, listener: (this: HTMLDnnRmUploadFileElement, ev: DnnRmUploadFileCustomEvent<HTMLDnnRmUploadFileElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDnnRmUploadFileElementEventMap>(type: K, listener: (this: HTMLDnnRmUploadFileElement, ev: DnnRmUploadFileCustomEvent<HTMLDnnRmUploadFileElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDnnRmUploadFileElement: {
        prototype: HTMLDnnRmUploadFileElement;
        new (): HTMLDnnRmUploadFileElement;
    };
    interface HTMLElementTagNameMap {
        "dnn-action-copy-url": HTMLDnnActionCopyUrlElement;
        "dnn-action-create-folder": HTMLDnnActionCreateFolderElement;
        "dnn-action-delete-items": HTMLDnnActionDeleteItemsElement;
        "dnn-action-download-item": HTMLDnnActionDownloadItemElement;
        "dnn-action-edit-item": HTMLDnnActionEditItemElement;
        "dnn-action-move-items": HTMLDnnActionMoveItemsElement;
        "dnn-action-open-file": HTMLDnnActionOpenFileElement;
        "dnn-action-unlink-items": HTMLDnnActionUnlinkItemsElement;
        "dnn-action-upload-file": HTMLDnnActionUploadFileElement;
        "dnn-resource-manager": HTMLDnnResourceManagerElement;
        "dnn-rm-actions-bar": HTMLDnnRmActionsBarElement;
        "dnn-rm-create-folder": HTMLDnnRmCreateFolderElement;
        "dnn-rm-delete-items": HTMLDnnRmDeleteItemsElement;
        "dnn-rm-edit-file": HTMLDnnRmEditFileElement;
        "dnn-rm-edit-folder": HTMLDnnRmEditFolderElement;
        "dnn-rm-file-context-menu": HTMLDnnRmFileContextMenuElement;
        "dnn-rm-files-pane": HTMLDnnRmFilesPaneElement;
        "dnn-rm-folder-context-menu": HTMLDnnRmFolderContextMenuElement;
        "dnn-rm-folder-list": HTMLDnnRmFolderListElement;
        "dnn-rm-folder-list-item": HTMLDnnRmFolderListItemElement;
        "dnn-rm-folder-mappings": HTMLDnnRmFolderMappingsElement;
        "dnn-rm-items-cardview": HTMLDnnRmItemsCardviewElement;
        "dnn-rm-items-listview": HTMLDnnRmItemsListviewElement;
        "dnn-rm-left-pane": HTMLDnnRmLeftPaneElement;
        "dnn-rm-move-items": HTMLDnnRmMoveItemsElement;
        "dnn-rm-progress-bar": HTMLDnnRmProgressBarElement;
        "dnn-rm-queued-file": HTMLDnnRmQueuedFileElement;
        "dnn-rm-right-pane": HTMLDnnRmRightPaneElement;
        "dnn-rm-status-bar": HTMLDnnRmStatusBarElement;
        "dnn-rm-top-bar": HTMLDnnRmTopBarElement;
        "dnn-rm-unlink-items": HTMLDnnRmUnlinkItemsElement;
        "dnn-rm-upload-file": HTMLDnnRmUploadFileElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface DnnActionCopyUrl {
        /**
          * The list of items to copy.
         */
        "items": Item[];
    }
    interface DnnActionCreateFolder {
        /**
          * The ID of the parent folder
         */
        "parentFolderId"?: number;
    }
    interface DnnActionDeleteItems {
        /**
          * The list of items to delete.
         */
        "items": Item[];
    }
    interface DnnActionDownloadItem {
        /**
          * The item to download.
         */
        "item": Item;
    }
    interface DnnActionEditItem {
        /**
          * The item to edit.
         */
        "item": Item;
    }
    interface DnnActionMoveItems {
        /**
          * The list of items to move.
         */
        "items": Item[];
    }
    interface DnnActionOpenFile {
        /**
          * The item to open.
         */
        "item": Item;
    }
    interface DnnActionUnlinkItems {
        /**
          * The list of items selected.
         */
        "items": Item[];
    }
    interface DnnActionUploadFile {
        /**
          * Fires when there is a possibility that some folders have changed. Can be used to force parts of the UI to refresh.
         */
        "onDnnRmFoldersChanged"?: (event: DnnActionUploadFileCustomEvent<void>) => void;
        /**
          * The ID of the parent folder.
         */
        "parentFolderId"?: number;
    }
    interface DnnResourceManager {
        /**
          * The ID of the module.
         */
        "moduleId": number;
    }
    interface DnnRmActionsBar {
    }
    interface DnnRmCreateFolder {
        /**
          * Fires when there is a possibility that some folders have changed. Can be used to force parts of the UI to refresh.
         */
        "onDnnRmFoldersChanged"?: (event: DnnRmCreateFolderCustomEvent<void>) => void;
    }
    interface DnnRmDeleteItems {
        /**
          * The list of items to delete.
         */
        "items": Item[];
        /**
          * Fires when there is a possibility that some folders have changed. Can be used to force parts of the UI to refresh.
         */
        "onDnnRmFoldersChanged"?: (event: DnnRmDeleteItemsCustomEvent<void>) => void;
    }
    interface DnnRmEditFile {
        /**
          * The ID of the folder to edit.
         */
        "fileId": number;
        /**
          * Fires when there is a possibility that some folders have changed. Can be used to force parts of the UI to refresh.
         */
        "onDnnRmFoldersChanged"?: (event: DnnRmEditFileCustomEvent<void>) => void;
    }
    interface DnnRmEditFolder {
        /**
          * The ID of the folder to edit.
         */
        "folderId": number;
        /**
          * Fires when there is a possibility that some folders have changed. Can be used to force parts of the UI to refresh.
         */
        "onDnnRmFoldersChanged"?: (event: DnnRmEditFolderCustomEvent<void>) => void;
    }
    interface DnnRmFileContextMenu {
        /**
          * The item that triggered this menu.
         */
        "item": Item;
    }
    interface DnnRmFilesPane {
        /**
          * Defines how much more pixels to load under the fold.
          * @default 5000
         */
        "preloadOffset"?: number;
    }
    interface DnnRmFolderContextMenu {
        /**
          * The item that triggered this menu.
         */
        "item": Item;
    }
    interface DnnRmFolderList {
        /**
          * Fires when a folder is picked.
         */
        "onDnnRmFolderListFolderPicked"?: (event: DnnRmFolderListCustomEvent<FolderTreeItem>) => void;
        /**
          * Fires when a context menu is opened for this item. Emits the folder ID.
         */
        "onDnnRmcontextMenuOpened"?: (event: DnnRmFolderListCustomEvent<number>) => void;
    }
    interface DnnRmFolderListItem {
        /**
          * If true, this node will be expanded on load.
          * @default false
         */
        "expanded"?: boolean;
        /**
          * The basic information about the folder
         */
        "folder": FolderTreeItem;
        /**
          * Fires when a folder is clicked.
         */
        "onDnnRmFolderListItemClicked"?: (event: DnnRmFolderListItemCustomEvent<FolderTreeItem>) => void;
        /**
          * The ID of the parent folder.
         */
        "parentFolderId": number;
        /**
          * Indicates if this item is the currently selected one.
         */
        "selectedFolder"?: FolderTreeItem;
    }
    interface DnnRmFolderMappings {
    }
    interface DnnRmItemsCardview {
        /**
          * The list of current items.
         */
        "currentItems": GetFolderContentResponse;
        /**
          * Fires when a file is double-clicked and emits the file ID into the event.detail
         */
        "onDnnRmFileDoubleClicked"?: (event: DnnRmItemsCardviewCustomEvent<string>) => void;
        /**
          * Fires when a folder is double-clicked and emits the folder ID into the event.detail
         */
        "onDnnRmFolderDoubleClicked"?: (event: DnnRmItemsCardviewCustomEvent<number>) => void;
    }
    interface DnnRmItemsListview {
        /**
          * The list of current items.
         */
        "currentItems": GetFolderContentResponse;
        /**
          * Fires when a file is double-clicked and emits the file ID into the event.detail
         */
        "onDnnRmFileDoubleClicked"?: (event: DnnRmItemsListviewCustomEvent<string>) => void;
        /**
          * Fires when a folder is double-clicked and emits the folder ID into the event.detail
         */
        "onDnnRmFolderDoubleClicked"?: (event: DnnRmItemsListviewCustomEvent<number>) => void;
    }
    interface DnnRmLeftPane {
    }
    interface DnnRmMoveItems {
        /**
          * The list of items to delete.
         */
        "items": Item[];
        /**
          * Fires when there is a possibility that some folders have changed. Can be used to force parts of the UI to refresh.
         */
        "onDnnRmFoldersChanged"?: (event: DnnRmMoveItemsCustomEvent<void>) => void;
    }
    interface DnnRmProgressBar {
        /**
          * Defines the max progress value.
          * @default 100
         */
        "max"?: number;
        /**
          * Defines the current progress value.
          * @default 0
         */
        "value"?: number;
    }
    interface DnnRmQueuedFile {
        /**
          * Whether to extract uploaded zip files.
          * @default false
         */
        "extract"?: boolean;
        /**
          * The file to upload.
         */
        "file": File;
        /**
          * Optionally limit the file types that can be uploaded.
         */
        "filter": string;
        /**
          * The maximal allowed file upload size
         */
        "maxUploadFileSize": number;
        /**
          * The validation code to use for uploads.
         */
        "validationCode": string;
    }
    interface DnnRmRightPane {
    }
    interface DnnRmStatusBar {
    }
    interface DnnRmTopBar {
    }
    interface DnnRmUnlinkItems {
        /**
          * The list of items to delete.
         */
        "items": Item[];
        /**
          * Fires when there is a possibility that some folders have changed. Can be used to force parts of the UI to refresh.
         */
        "onDnnRmFoldersChanged"?: (event: DnnRmUnlinkItemsCustomEvent<void>) => void;
    }
    interface DnnRmUploadFile {
        /**
          * Fires when there is a possibility that some folders have changed. Can be used to force parts of the UI to refresh.
         */
        "onDnnRmFoldersChanged"?: (event: DnnRmUploadFileCustomEvent<void>) => void;
    }

    interface DnnActionCreateFolderAttributes {
        "parentFolderId": number;
    }
    interface DnnActionUploadFileAttributes {
        "parentFolderId": number;
    }
    interface DnnResourceManagerAttributes {
        "moduleId": number;
    }
    interface DnnRmEditFileAttributes {
        "fileId": number;
    }
    interface DnnRmEditFolderAttributes {
        "folderId": number;
    }
    interface DnnRmFilesPaneAttributes {
        "preloadOffset": number;
    }
    interface DnnRmFolderListItemAttributes {
        "expanded": boolean;
        "parentFolderId": number;
    }
    interface DnnRmProgressBarAttributes {
        "value": number;
        "max": number;
    }
    interface DnnRmQueuedFileAttributes {
        "extract": boolean;
        "validationCode": string;
        "filter": string;
        "maxUploadFileSize": number;
    }

    interface IntrinsicElements {
        "dnn-action-copy-url": DnnActionCopyUrl;
        "dnn-action-create-folder": Omit<DnnActionCreateFolder, keyof DnnActionCreateFolderAttributes> & { [K in keyof DnnActionCreateFolder & keyof DnnActionCreateFolderAttributes]?: DnnActionCreateFolder[K] } & { [K in keyof DnnActionCreateFolder & keyof DnnActionCreateFolderAttributes as `attr:${K}`]?: DnnActionCreateFolderAttributes[K] } & { [K in keyof DnnActionCreateFolder & keyof DnnActionCreateFolderAttributes as `prop:${K}`]?: DnnActionCreateFolder[K] };
        "dnn-action-delete-items": DnnActionDeleteItems;
        "dnn-action-download-item": DnnActionDownloadItem;
        "dnn-action-edit-item": DnnActionEditItem;
        "dnn-action-move-items": DnnActionMoveItems;
        "dnn-action-open-file": DnnActionOpenFile;
        "dnn-action-unlink-items": DnnActionUnlinkItems;
        "dnn-action-upload-file": Omit<DnnActionUploadFile, keyof DnnActionUploadFileAttributes> & { [K in keyof DnnActionUploadFile & keyof DnnActionUploadFileAttributes]?: DnnActionUploadFile[K] } & { [K in keyof DnnActionUploadFile & keyof DnnActionUploadFileAttributes as `attr:${K}`]?: DnnActionUploadFileAttributes[K] } & { [K in keyof DnnActionUploadFile & keyof DnnActionUploadFileAttributes as `prop:${K}`]?: DnnActionUploadFile[K] };
        "dnn-resource-manager": Omit<DnnResourceManager, keyof DnnResourceManagerAttributes> & { [K in keyof DnnResourceManager & keyof DnnResourceManagerAttributes]?: DnnResourceManager[K] } & { [K in keyof DnnResourceManager & keyof DnnResourceManagerAttributes as `attr:${K}`]?: DnnResourceManagerAttributes[K] } & { [K in keyof DnnResourceManager & keyof DnnResourceManagerAttributes as `prop:${K}`]?: DnnResourceManager[K] } & OneOf<"moduleId", DnnResourceManager["moduleId"], DnnResourceManagerAttributes["moduleId"]>;
        "dnn-rm-actions-bar": DnnRmActionsBar;
        "dnn-rm-create-folder": DnnRmCreateFolder;
        "dnn-rm-delete-items": DnnRmDeleteItems;
        "dnn-rm-edit-file": Omit<DnnRmEditFile, keyof DnnRmEditFileAttributes> & { [K in keyof DnnRmEditFile & keyof DnnRmEditFileAttributes]?: DnnRmEditFile[K] } & { [K in keyof DnnRmEditFile & keyof DnnRmEditFileAttributes as `attr:${K}`]?: DnnRmEditFileAttributes[K] } & { [K in keyof DnnRmEditFile & keyof DnnRmEditFileAttributes as `prop:${K}`]?: DnnRmEditFile[K] } & OneOf<"fileId", DnnRmEditFile["fileId"], DnnRmEditFileAttributes["fileId"]>;
        "dnn-rm-edit-folder": Omit<DnnRmEditFolder, keyof DnnRmEditFolderAttributes> & { [K in keyof DnnRmEditFolder & keyof DnnRmEditFolderAttributes]?: DnnRmEditFolder[K] } & { [K in keyof DnnRmEditFolder & keyof DnnRmEditFolderAttributes as `attr:${K}`]?: DnnRmEditFolderAttributes[K] } & { [K in keyof DnnRmEditFolder & keyof DnnRmEditFolderAttributes as `prop:${K}`]?: DnnRmEditFolder[K] } & OneOf<"folderId", DnnRmEditFolder["folderId"], DnnRmEditFolderAttributes["folderId"]>;
        "dnn-rm-file-context-menu": DnnRmFileContextMenu;
        "dnn-rm-files-pane": Omit<DnnRmFilesPane, keyof DnnRmFilesPaneAttributes> & { [K in keyof DnnRmFilesPane & keyof DnnRmFilesPaneAttributes]?: DnnRmFilesPane[K] } & { [K in keyof DnnRmFilesPane & keyof DnnRmFilesPaneAttributes as `attr:${K}`]?: DnnRmFilesPaneAttributes[K] } & { [K in keyof DnnRmFilesPane & keyof DnnRmFilesPaneAttributes as `prop:${K}`]?: DnnRmFilesPane[K] };
        "dnn-rm-folder-context-menu": DnnRmFolderContextMenu;
        "dnn-rm-folder-list": DnnRmFolderList;
        "dnn-rm-folder-list-item": Omit<DnnRmFolderListItem, keyof DnnRmFolderListItemAttributes> & { [K in keyof DnnRmFolderListItem & keyof DnnRmFolderListItemAttributes]?: DnnRmFolderListItem[K] } & { [K in keyof DnnRmFolderListItem & keyof DnnRmFolderListItemAttributes as `attr:${K}`]?: DnnRmFolderListItemAttributes[K] } & { [K in keyof DnnRmFolderListItem & keyof DnnRmFolderListItemAttributes as `prop:${K}`]?: DnnRmFolderListItem[K] } & OneOf<"parentFolderId", DnnRmFolderListItem["parentFolderId"], DnnRmFolderListItemAttributes["parentFolderId"]>;
        "dnn-rm-folder-mappings": DnnRmFolderMappings;
        "dnn-rm-items-cardview": DnnRmItemsCardview;
        "dnn-rm-items-listview": DnnRmItemsListview;
        "dnn-rm-left-pane": DnnRmLeftPane;
        "dnn-rm-move-items": DnnRmMoveItems;
        "dnn-rm-progress-bar": Omit<DnnRmProgressBar, keyof DnnRmProgressBarAttributes> & { [K in keyof DnnRmProgressBar & keyof DnnRmProgressBarAttributes]?: DnnRmProgressBar[K] } & { [K in keyof DnnRmProgressBar & keyof DnnRmProgressBarAttributes as `attr:${K}`]?: DnnRmProgressBarAttributes[K] } & { [K in keyof DnnRmProgressBar & keyof DnnRmProgressBarAttributes as `prop:${K}`]?: DnnRmProgressBar[K] };
        "dnn-rm-queued-file": Omit<DnnRmQueuedFile, keyof DnnRmQueuedFileAttributes> & { [K in keyof DnnRmQueuedFile & keyof DnnRmQueuedFileAttributes]?: DnnRmQueuedFile[K] } & { [K in keyof DnnRmQueuedFile & keyof DnnRmQueuedFileAttributes as `attr:${K}`]?: DnnRmQueuedFileAttributes[K] } & { [K in keyof DnnRmQueuedFile & keyof DnnRmQueuedFileAttributes as `prop:${K}`]?: DnnRmQueuedFile[K] } & OneOf<"validationCode", DnnRmQueuedFile["validationCode"], DnnRmQueuedFileAttributes["validationCode"]> & OneOf<"filter", DnnRmQueuedFile["filter"], DnnRmQueuedFileAttributes["filter"]> & OneOf<"maxUploadFileSize", DnnRmQueuedFile["maxUploadFileSize"], DnnRmQueuedFileAttributes["maxUploadFileSize"]>;
        "dnn-rm-right-pane": DnnRmRightPane;
        "dnn-rm-status-bar": DnnRmStatusBar;
        "dnn-rm-top-bar": DnnRmTopBar;
        "dnn-rm-unlink-items": DnnRmUnlinkItems;
        "dnn-rm-upload-file": DnnRmUploadFile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dnn-action-copy-url": LocalJSX.IntrinsicElements["dnn-action-copy-url"] & JSXBase.HTMLAttributes<HTMLDnnActionCopyUrlElement>;
            "dnn-action-create-folder": LocalJSX.IntrinsicElements["dnn-action-create-folder"] & JSXBase.HTMLAttributes<HTMLDnnActionCreateFolderElement>;
            "dnn-action-delete-items": LocalJSX.IntrinsicElements["dnn-action-delete-items"] & JSXBase.HTMLAttributes<HTMLDnnActionDeleteItemsElement>;
            "dnn-action-download-item": LocalJSX.IntrinsicElements["dnn-action-download-item"] & JSXBase.HTMLAttributes<HTMLDnnActionDownloadItemElement>;
            "dnn-action-edit-item": LocalJSX.IntrinsicElements["dnn-action-edit-item"] & JSXBase.HTMLAttributes<HTMLDnnActionEditItemElement>;
            "dnn-action-move-items": LocalJSX.IntrinsicElements["dnn-action-move-items"] & JSXBase.HTMLAttributes<HTMLDnnActionMoveItemsElement>;
            "dnn-action-open-file": LocalJSX.IntrinsicElements["dnn-action-open-file"] & JSXBase.HTMLAttributes<HTMLDnnActionOpenFileElement>;
            "dnn-action-unlink-items": LocalJSX.IntrinsicElements["dnn-action-unlink-items"] & JSXBase.HTMLAttributes<HTMLDnnActionUnlinkItemsElement>;
            "dnn-action-upload-file": LocalJSX.IntrinsicElements["dnn-action-upload-file"] & JSXBase.HTMLAttributes<HTMLDnnActionUploadFileElement>;
            "dnn-resource-manager": LocalJSX.IntrinsicElements["dnn-resource-manager"] & JSXBase.HTMLAttributes<HTMLDnnResourceManagerElement>;
            "dnn-rm-actions-bar": LocalJSX.IntrinsicElements["dnn-rm-actions-bar"] & JSXBase.HTMLAttributes<HTMLDnnRmActionsBarElement>;
            "dnn-rm-create-folder": LocalJSX.IntrinsicElements["dnn-rm-create-folder"] & JSXBase.HTMLAttributes<HTMLDnnRmCreateFolderElement>;
            "dnn-rm-delete-items": LocalJSX.IntrinsicElements["dnn-rm-delete-items"] & JSXBase.HTMLAttributes<HTMLDnnRmDeleteItemsElement>;
            "dnn-rm-edit-file": LocalJSX.IntrinsicElements["dnn-rm-edit-file"] & JSXBase.HTMLAttributes<HTMLDnnRmEditFileElement>;
            "dnn-rm-edit-folder": LocalJSX.IntrinsicElements["dnn-rm-edit-folder"] & JSXBase.HTMLAttributes<HTMLDnnRmEditFolderElement>;
            "dnn-rm-file-context-menu": LocalJSX.IntrinsicElements["dnn-rm-file-context-menu"] & JSXBase.HTMLAttributes<HTMLDnnRmFileContextMenuElement>;
            "dnn-rm-files-pane": LocalJSX.IntrinsicElements["dnn-rm-files-pane"] & JSXBase.HTMLAttributes<HTMLDnnRmFilesPaneElement>;
            "dnn-rm-folder-context-menu": LocalJSX.IntrinsicElements["dnn-rm-folder-context-menu"] & JSXBase.HTMLAttributes<HTMLDnnRmFolderContextMenuElement>;
            "dnn-rm-folder-list": LocalJSX.IntrinsicElements["dnn-rm-folder-list"] & JSXBase.HTMLAttributes<HTMLDnnRmFolderListElement>;
            "dnn-rm-folder-list-item": LocalJSX.IntrinsicElements["dnn-rm-folder-list-item"] & JSXBase.HTMLAttributes<HTMLDnnRmFolderListItemElement>;
            "dnn-rm-folder-mappings": LocalJSX.IntrinsicElements["dnn-rm-folder-mappings"] & JSXBase.HTMLAttributes<HTMLDnnRmFolderMappingsElement>;
            "dnn-rm-items-cardview": LocalJSX.IntrinsicElements["dnn-rm-items-cardview"] & JSXBase.HTMLAttributes<HTMLDnnRmItemsCardviewElement>;
            "dnn-rm-items-listview": LocalJSX.IntrinsicElements["dnn-rm-items-listview"] & JSXBase.HTMLAttributes<HTMLDnnRmItemsListviewElement>;
            "dnn-rm-left-pane": LocalJSX.IntrinsicElements["dnn-rm-left-pane"] & JSXBase.HTMLAttributes<HTMLDnnRmLeftPaneElement>;
            "dnn-rm-move-items": LocalJSX.IntrinsicElements["dnn-rm-move-items"] & JSXBase.HTMLAttributes<HTMLDnnRmMoveItemsElement>;
            "dnn-rm-progress-bar": LocalJSX.IntrinsicElements["dnn-rm-progress-bar"] & JSXBase.HTMLAttributes<HTMLDnnRmProgressBarElement>;
            "dnn-rm-queued-file": LocalJSX.IntrinsicElements["dnn-rm-queued-file"] & JSXBase.HTMLAttributes<HTMLDnnRmQueuedFileElement>;
            "dnn-rm-right-pane": LocalJSX.IntrinsicElements["dnn-rm-right-pane"] & JSXBase.HTMLAttributes<HTMLDnnRmRightPaneElement>;
            "dnn-rm-status-bar": LocalJSX.IntrinsicElements["dnn-rm-status-bar"] & JSXBase.HTMLAttributes<HTMLDnnRmStatusBarElement>;
            "dnn-rm-top-bar": LocalJSX.IntrinsicElements["dnn-rm-top-bar"] & JSXBase.HTMLAttributes<HTMLDnnRmTopBarElement>;
            "dnn-rm-unlink-items": LocalJSX.IntrinsicElements["dnn-rm-unlink-items"] & JSXBase.HTMLAttributes<HTMLDnnRmUnlinkItemsElement>;
            "dnn-rm-upload-file": LocalJSX.IntrinsicElements["dnn-rm-upload-file"] & JSXBase.HTMLAttributes<HTMLDnnRmUploadFileElement>;
        }
    }
}
