//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDependency.TypeScript {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsLibs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsLibs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientDependency.TypeScript.JsLibs", typeof(JsLibs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //global compilation method
        ///function compileTsSource(source) {
        ///    var compiler = new tsCompiler();
        ///    compiler.compile(source);
        ///    return compiler.getResult();
        ///}
        ///
        /////compiler class
        ///function tsCompiler() {
        ///    //internal props
        ///    this.output = &quot;&quot;;
        ///    this.libfile = &apos;/// &lt;reference no-default-lib=&quot;true&quot;/&gt;\n&apos; +
        ///        &apos;declare var NaN:number;\ndeclare var Infinity:number;\ndeclare function eval(x:string):any;\ndeclare function parseInt(s:string,radix?:number):number;\ndeclare function parseFlo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string compiler {
            get {
                return ResourceManager.GetString("compiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* *****************************************************************************
        ///Copyright (c) Microsoft Corporation. All rights reserved. 
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use
        ///this file except in compliance with the License. You may obtain a copy of the
        ///License at http://www.apache.org/licenses/LICENSE-2.0  
        /// 
        ///THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
        ///KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lib_d {
            get {
                return ResourceManager.GetString("lib_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* *****************************************************************************
        ///Copyright (c) Microsoft Corporation. All rights reserved. 
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use
        ///this file except in compliance with the License. You may obtain a copy of the
        ///License at http://www.apache.org/licenses/LICENSE-2.0  
        /// 
        ///THIS CODE IS PROVIDED *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
        ///KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string typescript_min {
            get {
                return ResourceManager.GetString("typescript_min", resourceCulture);
            }
        }
    }
}
