import { createStore } from "@stencil/store";
import { BulkInstallLocalization } from "../clients/localization-client";

const { state } = createStore<IBulkInstallState>({
  resx: {
    Action: "Action",
    Add: "Add",
    All: "All",
    ApiError: "There was an error communicating with the API, please check the Admin Logs for more details",
    ApiAuthDisabled: "API Token authentication must be enabled in the web.config before creating API Users",
    ApiKey: "API Key",
    ApiUserNameText: "Name",
    ApiUserNameHelp: "Enter API User Name",
    ApiUserExpiresOnText: "Expires On",
    ApiUserExpiresOnHelp: "Expiration of the API User",
    ApiUsers: "API Users",
    BulkInstall: "Bulk Install",
    BypassIpAllowList: "Bypass IP Allow List",
    Cancel: "Cancel",
    CannotInstall: "One or more of the uploaded packages cannot be installed",
    Close: "Close",
    Copy: "Copy",
    Create: "Create",
    Date: "Date",
    Delete: "Delete",
    EnableIpSafeList: "Enable IP Safelist",
    EncryptionKey: "Encryption Key",
    Events: "Events",
    EventLogSeverity_Info: "Info",
    EventLogSeverity_Warning: "Warning",
    EventLogSeverity_Alert: "Alert",
    EventLogSeverity_Critical: "Critical",
    FileUploadedMessage: "Package uploaded",
    Install: "Install",
    InstallationComplete: "Installation Complete!",
    InstallingPackages: "Installing Package(s)",
    IPAddress: "IP Address",
    IPSafeList: "IP Safelist",
    IPSafeListConfiguration: "IP Safelist Configuration",
    IPSafeListEntries: "IP Safelist Entries",
    IPSafeListItemNameText: "Name",
    IPSafeListItemNameHelp: "Enter a friendly name for this IP Address",
    IPSafeListItemIpAddressText: "IP Address",
    IPSafeListItemIpAddressHelp: "Enter IP Address to allow",
    Logs: "Logs",
    Message: "Message",
    Name: "Name",
    NewApiUser: "New API User",
    NewApiUserCredentialsTitle: "API User Credentials",
    NewApiUserCredentialsWarning: "These credentials are shown only once. Copy and store them before closing this dialog.",
    NewIpSafelistEntry: "New IP Safelist Entry",
    Packages: "Packages",
    PackageDependencies: "Dependencies",
    PlatformVersion: "Platform Version",
    Reset: "Reset",
    Save: "Save",
    SessionStatus_NotStarted: "Not Started",
    SessionStatus_InProgress: "In Progress",
    SessionStatus_Complete: "Complete",
    Severity: "Severity",
    Type: "Type",
    UploadInstallPackages: "Upload Install Package(s)",
    DropZone_DragAndDropFile: "Drag and drop package files",
    DropZone_Or: "or",
    DropZone_UploadFile: "Upload package files",
    DropZone_UploadSizeTooLarge: "One or more of the files you tried to upload is too large.",
    DropZone_FileSizeLimit: "The maximum size is {0}",
    DropZone_InvalidExtension: "One or more of the files you tried to upload has an invalid extension.",
    DropZone_AllowedFileExtensions: "Allowed file extensions: {0}",
  },
  moduleId: -1,
});

interface IBulkInstallState {
  resx: BulkInstallLocalization;
  moduleId: number;
}

export default state;
