/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BulkInstallApiUsers {
    }
    interface BulkInstallInstall {
    }
    interface BulkInstallIpSafelist {
    }
    interface BulkInstallLogs {
    }
    interface DnnBulkInstall {
    }
}
declare global {
    interface HTMLBulkInstallApiUsersElement extends Components.BulkInstallApiUsers, HTMLStencilElement {
    }
    var HTMLBulkInstallApiUsersElement: {
        prototype: HTMLBulkInstallApiUsersElement;
        new (): HTMLBulkInstallApiUsersElement;
    };
    interface HTMLBulkInstallInstallElement extends Components.BulkInstallInstall, HTMLStencilElement {
    }
    var HTMLBulkInstallInstallElement: {
        prototype: HTMLBulkInstallInstallElement;
        new (): HTMLBulkInstallInstallElement;
    };
    interface HTMLBulkInstallIpSafelistElement extends Components.BulkInstallIpSafelist, HTMLStencilElement {
    }
    var HTMLBulkInstallIpSafelistElement: {
        prototype: HTMLBulkInstallIpSafelistElement;
        new (): HTMLBulkInstallIpSafelistElement;
    };
    interface HTMLBulkInstallLogsElement extends Components.BulkInstallLogs, HTMLStencilElement {
    }
    var HTMLBulkInstallLogsElement: {
        prototype: HTMLBulkInstallLogsElement;
        new (): HTMLBulkInstallLogsElement;
    };
    interface HTMLDnnBulkInstallElement extends Components.DnnBulkInstall, HTMLStencilElement {
    }
    var HTMLDnnBulkInstallElement: {
        prototype: HTMLDnnBulkInstallElement;
        new (): HTMLDnnBulkInstallElement;
    };
    interface HTMLElementTagNameMap {
        "bulk-install-api-users": HTMLBulkInstallApiUsersElement;
        "bulk-install-install": HTMLBulkInstallInstallElement;
        "bulk-install-ip-safelist": HTMLBulkInstallIpSafelistElement;
        "bulk-install-logs": HTMLBulkInstallLogsElement;
        "dnn-bulk-install": HTMLDnnBulkInstallElement;
    }
}
declare namespace LocalJSX {
    interface BulkInstallApiUsers {
    }
    interface BulkInstallInstall {
    }
    interface BulkInstallIpSafelist {
    }
    interface BulkInstallLogs {
    }
    interface DnnBulkInstall {
    }
    interface IntrinsicElements {
        "bulk-install-api-users": BulkInstallApiUsers;
        "bulk-install-install": BulkInstallInstall;
        "bulk-install-ip-safelist": BulkInstallIpSafelist;
        "bulk-install-logs": BulkInstallLogs;
        "dnn-bulk-install": DnnBulkInstall;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bulk-install-api-users": LocalJSX.BulkInstallApiUsers & JSXBase.HTMLAttributes<HTMLBulkInstallApiUsersElement>;
            "bulk-install-install": LocalJSX.BulkInstallInstall & JSXBase.HTMLAttributes<HTMLBulkInstallInstallElement>;
            "bulk-install-ip-safelist": LocalJSX.BulkInstallIpSafelist & JSXBase.HTMLAttributes<HTMLBulkInstallIpSafelistElement>;
            "bulk-install-logs": LocalJSX.BulkInstallLogs & JSXBase.HTMLAttributes<HTMLBulkInstallLogsElement>;
            "dnn-bulk-install": LocalJSX.DnnBulkInstall & JSXBase.HTMLAttributes<HTMLDnnBulkInstallElement>;
        }
    }
}
