/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ApiUsers {
    }
    interface DnnBulkInstall {
    }
}
declare global {
    interface HTMLApiUsersElement extends Components.ApiUsers, HTMLStencilElement {
    }
    var HTMLApiUsersElement: {
        prototype: HTMLApiUsersElement;
        new (): HTMLApiUsersElement;
    };
    interface HTMLDnnBulkInstallElement extends Components.DnnBulkInstall, HTMLStencilElement {
    }
    var HTMLDnnBulkInstallElement: {
        prototype: HTMLDnnBulkInstallElement;
        new (): HTMLDnnBulkInstallElement;
    };
    interface HTMLElementTagNameMap {
        "api-users": HTMLApiUsersElement;
        "dnn-bulk-install": HTMLDnnBulkInstallElement;
    }
}
declare namespace LocalJSX {
    interface ApiUsers {
    }
    interface DnnBulkInstall {
    }
    interface IntrinsicElements {
        "api-users": ApiUsers;
        "dnn-bulk-install": DnnBulkInstall;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "api-users": LocalJSX.ApiUsers & JSXBase.HTMLAttributes<HTMLApiUsersElement>;
            "dnn-bulk-install": LocalJSX.DnnBulkInstall & JSXBase.HTMLAttributes<HTMLDnnBulkInstallElement>;
        }
    }
}
