const languagesActionTypes =  {    
    RETRIEVED_SITESETTINGS_LANGUAGE_SETTINGS: "RETRIEVED_SITESETTINGS_LANGUAGE_SETTINGS",
    SITESETTINGS_LANGUAGE_SETTINGS_CLIENT_MODIFIED: "SITESETTINGS_LANGUAGE_SETTINGS_CLIENT_MODIFIED",
    UPDATED_SITESETTINGS_LANGUAGE_SETTINGS: "UPDATED_SITESETTINGS_LANGUAGE_SETTINGS",
    RETRIEVED_SITESETTINGS_LANGUAGES: "RETRIEVED_SITESETTINGS_LANGUAGES",
    RETRIEVED_SITESETTINGS_LANGUAGE: "RETRIEVED_SITESETTINGS_LANGUAGE",
    RETRIEVED_SITESETTINGS_ALL_LANGUAGES: "RETRIEVED_SITESETTINGS_ALL_LANGUAGES",
    SITESETTINGS_LANGUAGE_CLIENT_MODIFIED: "SITESETTINGS_LANGUAGE_CLIENT_MODIFIED",
    CANCELED_SITESETTINGS_LANGUAGE_CLIENT_MODIFIED: "CANCELED_SITESETTINGS_LANGUAGE_CLIENT_MODIFIED",
    CREATED_SITESETTINGS_LANGUAGE: "CREATED_SITESETTINGS_LANGUAGE"
};
export default languagesActionTypes;
