const siteInfoActionTypes =  {    
    RETRIEVED_SITESETTINGS_PORTAL_SETTINGS: "RETRIEVED_SITESETTINGS_PORTAL_SETTINGS",
    UPDATED_SITESETTINGS_PORTAL_SETTINGS: "UPDATED_SITESETTINGS_PORTAL_SETTINGS",
    SITESETTINGS_PORTAL_SETTINS_CLIENT_MODIFIED: "SITESETTINGS_PORTAL_SETTINS_CLIENT_MODIFIED"    
};
export default siteInfoActionTypes;
