const portalActionTypes = {
    RETRIEVED_PORTALS: "RETRIEVED_PORTALS",
    RETRIEVED_PORTALS_CONCAT: "RETRIEVED_PORTALS_CONCAT",
    UPDATE_PORTAL_PARAMETER: "UPDATE_PORTAL_PARAMETER",
    RETRIEVED_PORTAL_TEMPLATES: "RETRIEVED_PORTAL_TEMPLATES",
    RETRIEVED_PORTAL_TABS_DESCENDANTS: "RETRIEVED_PORTAL_TABS_DESCENDANTS",
    RETRIEVED_PORTAL_TABS: "RETRIEVED_PORTAL_TABS",
    CREATED_PORTAL: "CREATED_PORTAL",
    DELETED_PORTAL: "DELETED_PORTAL",
    EXPORTED_PORTAL_TEMPLATE: "EXPORTED_PORTAL_TEMPLATE",
    SET_PORTAL_BEING_EXPORTED: "SET_PORTAL_BEING_EXPORTED"
};
export default portalActionTypes;
