const performanceTab =  {
    LOAD_PERFORMANCE_TAB: "LOAD_PERFORMANCE_TAB",
    LOADED_PERFORMANCE_TAB: "LOADED_PERFORMANCE_TAB",
    ERROR_LOADING_PERFORMANCE_TAB: "ERROR_LOADING_PERFORMANCE_TAB"
};

export default performanceTab;