const server =  {
    REQUEST_RESTART_APPLICATION: "REQUEST_RESTART_APPLICATION",
    END_REQUEST_RESTART_APPLICATION: "END_REQUEST_RESTART_APPLICATION",
    ERROR_REQUEST_RESTART_APPLICATION: "ERROR_REQUEST_RESTART_APPLICATION"
};

export default server;