const server =  {
    REQUEST_RESTART_APPLICATION: "REQUEST_RESTART_APPLICATION",
    END_REQUEST_RESTART_APPLICATION: "END_REQUEST_RESTART_APPLICATION",
    ERROR_REQUEST_RESTART_APPLICATION: "ERROR_REQUEST_RESTART_APPLICATION",
    REQUEST_CLEAR_CACHE: "REQUEST_CLEAR_CACHE",
    END_REQUEST_CLEAR_CACHE: "END_REQUEST_CLEAR_CACHE",
    ERROR_REQUEST_CLEAR_CACHE: "ERROR_REQUEST_CLEAR_CACHE",
    LOAD_SERVER_INFO: "LOAD_SERVER_INFO",
    LOADED_SERVER_INFO: "LOADED_SERVER_INFO",
    ERROR_LOADING_SERVER_INFO: "ERROR_LOADING_SERVER_INFO"
};

export default server;