const smtpServerTab =  {
    LOAD_SMTP_SERVER_TAB: "LOAD_SMTP_SERVER_TAB",
    LOADED_SMTP_SERVER_TAB: "LOADED_SMTP_SERVER_TAB",
    ERROR_LOADING_SMTP_SERVER_TAB: "ERROR_LOADING_SMTP_SERVER_TAB"
};

export default smtpServerTab;