const smtpServerTab =  {
    LOAD_SMTP_SERVER_TAB: "LOAD_SMTP_SERVER_TAB",
    LOADED_SMTP_SERVER_TAB: "LOADED_SMTP_SERVER_TAB",
    ERROR_LOADING_SMTP_SERVER_TAB: "ERROR_LOADING_SMTP_SERVER_TAB",
    CHANGE_SMTP_SERVER_MODE: "CHANGE_SMTP_SERVER_MODE",
    CHANGE_SMTP_AUTHENTICATION: "CHANGE_SMTP_AUTHENTICATION",
    CHANGE_SMTP_CONFIGURATION_VALUE: "CHANGE_SMTP_CONFIGURATION_VALUE"
};

export default smtpServerTab;