const portalActionTypes = {
    RETRIEVED_PORTALS: "RETRIEVED_PORTALS",
    RETRIEVED_PORTAL_TEMPLATES: "RETRIEVED_PORTAL_TEMPLATES",
    RETRIEVED_PORTAL_TABS_DESCENDANTS: "RETRIEVED_PORTAL_TABS_DESCENDANTS",
    RETRIEVED_PORTAL_TABS: "RETRIEVED_PORTAL_TABS",
    CREATED_PORTAL_TEMPLATE: "CREATED_PORTAL_TEMPLATE",
    DELETED_PORTAL_TEMPLATE: "DELETED_PORTAL_TEMPLATE",
    EXPORTED_PORTAL_TEMPLATE: "EXPORTED_PORTAL_TEMPLATE",
    SET_PORTAL_BEING_EXPORTED: "SET_PORTAL_BEING_EXPORTED"
};
export default portalActionTypes;
