//HintName: Example.Test.Page.cs
// <auto-generated/>
namespace Example.Test;

[global::System.Obsolete(@"Deprecated in DotNetNuke 9.1.2. Use PageMaker.MakePage(""PageType0""). Scheduled for removal in v11.0.0.")]
partial class Page
{
}

