//HintName: Example.Test.PagesController`2.cs
// <auto-generated/>
namespace Example.Test;

[global::System.Obsolete(@"Deprecated in DotNetNuke 10.0.0. Please resolve IPagesController via dependency injection. Scheduled for removal in v12.0.0.")]
partial class PagesController<T,U>
{
}

