//HintName: Example.Test.Page.InnerPage.cs
// <auto-generated/>
namespace Example.Test;

partial class Page
{
    [global::System.Obsolete("Deprecated in DotNetNuke 9.1.2. Please use InnerPageInfo. Scheduled for removal in v11.0.0.")]
    partial record InnerPage
    {
    }
}

