//HintName: G.A.cs
// <auto-generated/>
#pragma warning disable CS3005 // Identifier differing only in case is not CLS-compliant
namespace G;

[global::System.Obsolete(@"Deprecated in DotNetNuke 10.0.0. Please use PageInfo. Scheduled for removal in v12.0.0.")]
partial record A
{
}

