//HintName: G.B.cs
// <auto-generated/>
#pragma warning disable
namespace G;

[global::System.Obsolete(@"Deprecated in DotNetNuke 10.0.0. Please use the other B. Scheduled for removal in v12.0.0.")]
partial interface B
{
}

