//HintName: G.A.K.M(int_NULLABLE_,int).cs
// <auto-generated/>
namespace G;

partial class A
{
    partial class K
    {
        [global::System.Obsolete(@"Deprecated in DotNetNuke 9.4.4. Use overload taking IApplicationStatusInfo. Scheduled for removal in v11.0.0.")]
        public static partial int?[] M(
            int? a = null,
            int b = -1);
    }
}

