//HintName: G.D`2.cs
// <auto-generated/>
namespace G;

[global::System.Obsolete(@"Deprecated in DotNetNuke 10.0.0. Please resolve B via dependency injection. Scheduled for removal in v12.0.0.")]
partial class D<T,U>
{
}

